input_sources:
  elevation_mapping_sensor:
    type: pointcloud
    topic: /rslidar/points
    queue_size: 1
    publish_on_update: true
    sensor_processor:
      type: laser
robot_base_frame_id: base_link
map_frame_id: odom_graph_msf
track_point_frame_id: base_link
sensor_frame_id: rslidar