# Sensor Params
sensor_params:
  ## Config
  useLioOdometry: true
  useWheelOdometry: false
  useVioOdometry: false
  ## Rates
  lioOdometryRate: 10
  wheelOdometryRate: 50
  vioOdometryRate: 50

# Noise Parameters
noise_params:
  ## LiDAR
  lioPoseUnaryNoiseDensity: [ 0.05, 0.05, 0.05, 0.01, 0.01, 0.01 ] # StdDev, ORDER RPY(rad) - XYZ(meters) First tests:  [ 1000.0, 1000.0, 1000.0, 2.0, 2.0, 2.0 ]
  ## Wheel
  wheelPoseBetweenNoiseDensity: [ 0.2, 0.2, 0.2, 0.005, 0.005, 0.005 ] # StdDev, [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
  ## VIO
  vioPoseBetweenNoiseDensity: [ 100.0, 100.0, 100.0, 0.1, 0.1, 0.1 ] # StdDev [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
  vioPoseUnaryNoiseDensity: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ] # StdDev, [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
