<?xml version="1.0"?>

<!-- This file contains plugins to simulate an Imu sensor attached to the robot. -->
<!-- Documentation can be found at http://wiki.ros.org/hector_gazebo_plugins -->

<robot name="smb" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- INCLUDE PLUGIN -->
  <xacro:include filename="$(find smb_description)/urdf/sensor_plugins/smb_rgbcamera.gazebo.xacro"/>


  <xacro:macro name="rgbcamera_cam" params="*origin id base_link simulation">
    <!--                              Camera  Properties 				          	-->
    <xacro:property name="rgbcamera_base_link"		value="${base_link}"/>
    <xacro:property name="rgbcamera_origin_rpy"		value="0 0 0"/>
    <xacro:property name="rgbcamera_origin_xyz"		value="0.29082 -0.04458 ${0.0955 + chassisHeight/2.0}"/>

    <xacro:property name="rgbcamera_update_rate"		value="2"/>
    <xacro:property name="rgbcamera_link"  			value="rgbcamera${id}_link"/>

    <link name="${rgbcamera_link}">
      <inertial>
        <mass value="0.01" /> <!-- [kg] -->
        <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://smb_description/urdf/new_payload/meshes/SMB_blackfly_camera.dae"/> 
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://smb_description/urdf/new_payload/meshes/SMB_blackfly_camera.dae"/> 
        </geometry>
      </collision>
      <material name="red">
          <color rgba="255 0 10 255"/>
        </material>
    </link>

      <gazebo reference="${rgbcamera_link}">
        <material>Gazebo/Red</material>
      </gazebo>

    <joint name="rgbcamera${id}_camera_joint" type="fixed">
      <!-- <origin xyz="${rgbcamera_origin_xyz}" rpy="${rgbcamera_origin_rpy}"/> -->
      <xacro:insert_block name="origin"/>
      <parent link="${rgbcamera_base_link}"/>
      <child link="${rgbcamera_link}"/>
    </joint>

      <gazebo reference="rgbcamera${id}_camera_joint">
        <disableFixedJointLumping>true</disableFixedJointLumping>
      </gazebo>

    <link name="rgbcamera${id}_optical_link"/>

    <joint name="rgbcamera${id}_camera_optical_joint" type="fixed">
      <origin xyz="0.0066 0 0" rpy="-1.57 0 -1.57"/>
      <parent link="${rgbcamera_link}"/>
      <child link="rgbcamera${id}_optical_link"/>
    </joint>

    <xacro:if value="${simulation}">
        <xacro:rgbcamera_camera_plugin name="rgb_camera" link_name="${rgbcamera_link}" rate="${rgbcamera_update_rate}"/>
    </xacro:if>


  </xacro:macro>
</robot>
