# Sensor Params
sensor_params:
  ## Config
  useLioOdometry: true
  useWheelOdometry: false
  useVioOdometry: false
  ## Rates
  lioOdometryRate: 10
  wheelOdometryRate: 50
  vioOdometryRate: 50

# Alignment Parameters
alignment_params:
  initialSe3AlignmentNoiseDensity: [ 1.0e-01, 1.0e-01, 1.0e-01, 1.0e-02, 1.0e-02, 1.0e-02 ] # StdDev, ORDER RPY(rad) - XYZ(meters)

# Noise Parameters
noise_params:
  # IMU Random Walk
  # TODO: Change here
  accBiasRandomWalkNoiseDensity: 4.33e-05 # Continuous-time Noise Amplitude Spectral Density of Accelerometer bias random walk [m/s^3/√Hz], default: sqrt(1.0e-03)
  gyrBiasRandomWalkNoiseDensity: 2.66e-06 # Continuous-time Noise Amplitude Spectral Density of Gyroscope bias random walk [rad/s^2/√Hz], default: default: sqrt(9.33e-04)
  # TODO: End of change
  ## LiDAR
  lioPoseUnaryNoiseDensity: [ 0.05, 0.05, 0.05, 0.01, 0.01, 0.01 ] # StdDev, ORDER RPY(rad) - XYZ(meters) First tests:  [ 1000.0, 1000.0, 1000.0, 2.0, 2.0, 2.0 ]
  ## Wheel
  wheelPoseBetweenNoiseDensity: [ 0.2, 0.2, 0.2, 0.005, 0.005, 0.005 ] # StdDev, [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
  ## VIO
  vioPoseBetweenNoiseDensity: [ 100.0, 100.0, 100.0, 0.1, 0.1, 0.1 ] # StdDev [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
  vioPoseUnaryNoiseDensity: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ] # StdDev, [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
