# Factor Graph
graph_params:
  # TODO: Change here
  optimizeFixedFramePosesWrtWorld: false  # If true, the poses of the fixed frames are optimized w.r.t. world
  # TODO: End of change

# Sensor Params
sensor_params:
  ## Config
  useLioOdometry: true
  useWheelOdometry: false
  useVioOdometry: false
  ## Rates
  lioOdometryRate: 10
  wheelOdometryRate: 50
  vioOdometryRate: 50

# Alignment Parameters
alignment_params:
  initialSe3AlignmentNoiseDensity: [ 1.0e-01, 1.0e-01, 1.0e-01, 1.0e-02, 1.0e-02, 1.0e-02 ] # StdDev, ORDER RPY(rad) - XYZ(meters)

# Noise Parameters
noise_params:
  ## LiDAR
  lioPoseUnaryNoiseDensity: [ 0.05, 0.05, 0.05, 0.01, 0.01, 0.01 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## Wheel
  wheelPoseBetweenNoiseDensity: [ 0.1, 0.1, 0.1, 0.06, 0.06, 0.06 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## VIO
  vioPoseBetweenNoiseDensity: [ 100.0, 100.0, 100.0, 0.1, 0.1, 0.1 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  vioPoseUnaryNoiseDensity: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
