<?xml version="1.0"?>

<!-- This file contains plugins to simulate an Imu sensor attached to the robot. -->
<!-- Documentation can be found at http://wiki.ros.org/hector_gazebo_plugins -->

<robot name="smb" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="IMU" params="base_link simulation">
    <!--                              Imu  Properties 				          	-->
    <xacro:property name="imu_base_link"		value="${base_link}"/>
    <xacro:property name="imu_origin_rpy"		value="0 0 0"/>
    <!-- <xacro:property name="imu_origin_xyz"		value="0.27 -0.15 0.26"/> -->
    <xacro:property name="imu_origin_xyz"		value="0.2554 -0.02397 ${0.081+chassisHeight/2.0}"/>

    <xacro:property name="imu_update_rate"		value="400"/>
    <xacro:property name="imu_link"  			value="imu_link"/>
    <xacro:property name="imu_topic" 			value="/imu0"/>
    <xacro:property name="imu_calibration_service_name" value="/imu/calibrate"/>
    <xacro:property name="acceleration_offset"          value="0.0 0.0 0.0"/>
    <xacro:property name="acceleration_drift"           value="0.0 0.0 0.0"/>
    <xacro:property name="acceleration_drift_frequency" value="0.0 0.0 0.0"/>
    <xacro:property name="acceleration_gaussian_noise" 	value="0.0 0.0 0.0"/>
    <xacro:property name="rate_offset" 			value="0.0 0.0 0.0"/>
    <xacro:property name="rate_drift" 			value="0.0 0.0 0.0"/>
    <xacro:property name="rate_drift_frequency"	 	value="0.0 0.0 0.0"/>
    <xacro:property name="rate_gaussian_noise" 		value="0.0 0.0 0.0"/>
    <xacro:property name="heading_offset" 		value="0.0"/>
    <xacro:property name="heading_drift" 		value="0.0"/>
    <xacro:property name="heading_drift_frequency" 	value="0.0"/>
    <xacro:property name="heading_gaussian_noise" 	value="0.0"/>

    <xacro:if value="${simulation}">
    <gazebo>   
      <plugin name="smb_imu_plugin" filename="libhector_gazebo_ros_imu.so">
        <updateRate>${imu_update_rate}</updateRate>
        <bodyName>${imu_link}</bodyName>
        <frameId>${imu_link}</frameId>
        <topicName>${imu_topic}</topicName>
        <serviceName>${imu_calibration_service_name}</serviceName>
        <accelOffset>${acceleration_offset}</accelOffset>
        <accelDrift>${acceleration_drift}</accelDrift>
        <accelDriftFrequency>${acceleration_drift_frequency}</accelDriftFrequency>
        <accelGaussianNoise>${acceleration_gaussian_noise}</accelGaussianNoise>
        <rateOffset>${rate_offset}</rateOffset>
        <rateDrift>${rate_drift}</rateDrift>
        <rateDriftFrequency>${rate_drift_frequency}</rateDriftFrequency>
        <rateGaussianNoise>${rate_gaussian_noise}</rateGaussianNoise>
        <headingOffset>${heading_offset}</headingOffset>
        <headingDrift>${heading_drift}</headingDrift>
        <headingDriftFrequency>${heading_drift_frequency}</headingDriftFrequency>
        <headingGaussianNoise>${heading_gaussian_noise}</headingGaussianNoise>
      </plugin>
    </gazebo>
    </xacro:if>

    <!-- Imu is fixed to the base link -->
    <joint name="imu_joint" type="fixed">
      <origin xyz="${imu_origin_xyz}" rpy="${imu_origin_rpy}"/>
      <parent link="${imu_base_link}"/>
      <child link="${imu_link}"/>
    </joint>

    <!-- Imu link -->
    <link name="${imu_link}">
      <inertial>
        <mass value="0.001"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
        <!-- <box size="0.04 0.05 0.02"/> -->
        <mesh filename="package://smb_description/urdf/new_payload/meshes/SMB_imu.dae"/>
      </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <!-- <box size=".001 .001 .001"/> -->
          <mesh filename="package://smb_description/urdf/new_payload/meshes/SMB_imu.dae"/>
        </geometry>
      </collision>
      <material name="orange">
        <color rgba="255 108 10 255"/>
      </material>
    </link>

    <gazebo reference="${imu_link}">
      <material>Gazebo/Orange</material>
    </gazebo>


    <gazebo reference="imu_joint">
      <disableFixedJointLumping>true</disableFixedJointLumping>
    </gazebo>

  </xacro:macro> 
</robot> 
