world_frame: world
use_tf_transforms: True
use_freespace_pointcloud: True
tsdf_voxels_per_side: 16
tsdf_voxel_size: 0.20
max_ray_length_m: 50.0
truncation_distance: 0.6 #1.0
voxel_carving_enabled: True
use_sparsity_compensation_factor: True
sparsity_compensation_factor: 100.0 #10.0
color_mode: "colors"
verbose: False
update_mesh_every_n_sec: 0.5
mesh_min_weight: 1e-4
slice_level: 1.0
method: "fast"
integration_order_mode: "sorted"
max_consecutive_ray_collisions: 0
publish_slices: False
publish_pointclouds: True
allow_clear: True
pointcloud_queue_size: 1000
min_time_between_msgs_sec: 0.0
#max_block_distance_from_body: FLT_MAX
publish_tsdf_info: False
publish_slices: False
publish_traversable: True ###False
traversability_radius: 0.4 #0.4 ###1.5
enable_icp: False
icp_refine_roll_pitch: False
accumulate_icp_corrections: True
timestamp_tolerance_sec: 0.001 #0.001
publish_tsdf_map: True ###False
publish_esdf_map: True ###False

# ESDF #
esdf_max_distance_m: 2.0
clear_sphere_for_planning: False
clear_sphere_radius: 0.8

# OVERLAP BETWEEN VERSIONS #
use_const_weight: False
use_weight_dropoff: True
use_symmetric_weight_drop_off: False

### NEW SETTINGS FOR BRANCH feature/new_abort_criterion_for_fast_integrator ###
max_weight: 200 #20-200
clearing_ray_weight_factor: 0.01 #ANYmal: 0.01 #Flyab: 0.05 #0.05-1.0
weight_ray_by_range: False
min_ray_length_m: 0.5 #1.0
occupancy_min_distance_voxel_size_factor: 1.0
### THESE ARE OUT ###
# use_sparsity_compensation_factor
# sparsity_compensation_factor

# !!! NOT IMPLEMENTED FOR VOXBLOX !!!
# Augmentation
#augment_free_frustum_enabled: true
#free_frustum_skip: 10
#free_frustum_range: 15.0
#free_frustum_fov: [rad(2*pi), rad(pi/6)]
#free_frustum_resolution: [rad(1.0*pi/180) rad(1.0*pi/180)]